### ISSUE TITLE
instructions cannot be performed on windows

### ISSUE THREAD

**Issue by Amialc** [auth0-samples/auth0-ruby-api-samples#1]
Instructions in `start your server` [step](https://github.com/auth0-samples/auth0-ruby-api-samples/blob/master/README.md#start-your-server) are not compatible with windows. It should be like this `set AUDIENCE=<your API identifier>` (AUTH-3463)

**Comment by camimonse** [comment]
@Amialc  it is already like you describe, did you changed it? is there any PR that refers to this issue that needs to be linked?

**Comment by Amialc** [comment]
@camimonse no, i've not changed it and there is no pr with fix, issue is still there.

**Comment by camimonse** [comment]
this is fixed in #2

**Comment by chenkie** [comment]
Merged
